version: 2
jobs:
  build:
    docker:
      - image: goswagger/builder:20190630
    steps:
      - checkout

      - run:
          name: Run unit tests
          command: gotestsum -f short-verbose -- -timeout=20m -coverprofile=coverage.txt -covermode=atomic ./...
          no_output_timeout: 30m

      - run:
          name: Submit coverage results
          command: bash <(curl -s https://codecov.io/bash)

      - run:
          name: Save coverage html report
          command: |
            outputdir="/usr/share/coverage"
            if [[ ! -d ${outputdir} ]] ; then
                mkdir -p ${outputdir}
            fi
            gocov convert coverage.txt | gocov-html > ${outputdir}/coverage-${CIRCLE_BUILD_NUM-"0"}.html

      # Running the race detector is not supported on circleCI
      #- run:
      #    name: Run unit tests with race detector
      #    command: ./hack/test.sh --nocover
      #    no_output_timeout: 30m

      - run:
          name: Build docker images
          command: ./hack/build-docker.sh --circleci

      - run:
          name: Test codegen builds
          command: ./hack/codegen-nonreg.sh --circleci

      - run:
          name: Test canary builds
          command: ./hack/run-canary.sh

      - run:
          name: Prepare release
          command: |
            if echo $CIRCLE_TAG | grep -q -E "[0-9]+(\\.[0-9]+)*"; then
              . ./hack/deploy.sh

              prepare

              build_binary -os="linux darwin windows" -arch="amd64 386"
              build_binary -os="linux" -arch="arm64 arm"

              prepare_linuxpkg
              build_linuxpkg deb
              build_linuxpkg rpm
            fi

      - setup_remote_docker

      - deploy:
          name: Deploy release
          command: |
            if echo $CIRCLE_TAG | grep -q -E "[0-9]+(\\.[0-9]+)*"; then
              . ./hack/deploy.sh
              upload_to_github
              upload_to_bintray

              export EXTRA_TAG=latest
              deploy_docker
            fi

      - deploy:
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              export CIRCLE_TAG=dev
              . ./hack/deploy.sh
              deploy_docker
            fi

      - store_artifacts:
          path: /usr/share/dist

      - store_test_results:
          path: /usr/share/testresults
